// dasm6502.c 2013-08-27 generated by 6502x.py 
#include <stdio.h>
enum op6502types 

{
C_IMP,
C_IMM,
C_ACC,
C_ZERO,
C_ZEROX,
C_ZEROY,
C_ABS,
C_ABSX,
C_ABSY,
C_IND,
C_INDX,
C_INDY,
C_REL,
C_UNK
};

#define op_ ""
#define op_ADC "ADC"
#define op_AND "AND"
#define op_ASL "ASL"
#define op_BCC "BCC"
#define op_BCS "BCS"
#define op_BEQ "BEQ"
#define op_BIT "BIT"
#define op_BMI "BMI"
#define op_BNE "BNE"
#define op_BPL "BPL"
#define op_BRK "BRK"
#define op_BVC "BVC"
#define op_BVS "BVS"
#define op_CLC "CLC"
#define op_CLD "CLD"
#define op_CLI "CLI"
#define op_CLV "CLV"
#define op_CMP "CMP"
#define op_CPX "CPX"
#define op_CPY "CPY"
#define op_DEC "DEC"
#define op_DEX "DEX"
#define op_DEY "DEY"
#define op_EOR "EOR"
#define op_INC "INC"
#define op_INX "INX"
#define op_INY "INY"
#define op_JMP "JMP"
#define op_JSR "JSR"
#define op_LDA "LDA"
#define op_LDX "LDX"
#define op_LDY "LDY"
#define op_LSR "LSR"
#define op_NOP "NOP"
#define op_ORA "ORA"
#define op_PHA "PHA"
#define op_PHP "PHP"
#define op_PLA "PLA"
#define op_PLP "PLP"
#define op_ROL "ROL"
#define op_ROR "ROR"
#define op_RTI "RTI"
#define op_RTS "RTS"
#define op_SBC "SBC"
#define op_SEC "SEC"
#define op_SED "SED"
#define op_SEI "SEI"
#define op_STA "STA"
#define op_STX "STX"
#define op_STY "STY"
#define op_TAX "TAX"
#define op_TAY "TAY"
#define op_TSX "TSX"
#define op_TXA "TXA"
#define op_TXS "TXS"
#define op_TYA "TYA"

typedef struct
{
 char *name;
 int type;
 int len;
} opdef_t;

opdef_t op6502s[]= 
{

 {op_BRK, C_IMP, 1},
 {op_ORA, C_INDX, 2},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_ORA, C_ZERO, 2},
 {op_ASL, C_ZERO, 2},
 {op_, C_UNK, 1},
 {op_PHP, C_IMP, 1},
 {op_ORA, C_IMM, 2},
 {op_ASL, C_ACC, 1},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_ORA, C_ABS, 3},
 {op_ASL, C_ABS, 3},
 {op_, C_UNK, 1},
 {op_BPL, C_REL, 2},
 {op_ORA, C_INDY, 2},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_ORA, C_ZEROX, 2},
 {op_ASL, C_ZEROX, 2},
 {op_, C_UNK, 1},
 {op_CLC, C_IMP, 1},
 {op_ORA, C_ABSY, 3},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_ORA, C_ABSX, 3},
 {op_ASL, C_ABSX, 3},
 {op_, C_UNK, 1},
 {op_JSR, C_ABS, 3},
 {op_AND, C_INDX, 2},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_BIT, C_ZERO, 2},
 {op_AND, C_ZERO, 2},
 {op_ROL, C_ZERO, 2},
 {op_, C_UNK, 1},
 {op_PLP, C_IMP, 1},
 {op_AND, C_IMM, 2},
 {op_ROL, C_ACC, 1},
 {op_, C_UNK, 1},
 {op_BIT, C_ABS, 3},
 {op_AND, C_ABS, 3},
 {op_ROL, C_ABS, 3},
 {op_, C_UNK, 1},
 {op_BMI, C_REL, 2},
 {op_AND, C_INDY, 2},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_AND, C_ZEROX, 2},
 {op_ROL, C_ZEROX, 2},
 {op_, C_UNK, 1},
 {op_SEC, C_IMP, 1},
 {op_AND, C_ABSY, 3},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_AND, C_ABSX, 3},
 {op_ROL, C_ABSX, 3},
 {op_, C_UNK, 1},
 {op_RTI, C_IMP, 1},
 {op_EOR, C_INDX, 2},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_EOR, C_ZERO, 2},
 {op_LSR, C_ZERO, 2},
 {op_, C_UNK, 1},
 {op_PHA, C_IMP, 1},
 {op_EOR, C_IMM, 2},
 {op_LSR, C_ACC, 1},
 {op_, C_UNK, 1},
 {op_JMP, C_ABS, 3},
 {op_EOR, C_ABS, 3},
 {op_LSR, C_ABS, 3},
 {op_, C_UNK, 1},
 {op_BVC, C_REL, 2},
 {op_EOR, C_INDY, 2},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_EOR, C_ZEROX, 2},
 {op_LSR, C_ZEROX, 2},
 {op_, C_UNK, 1},
 {op_CLI, C_IMP, 1},
 {op_EOR, C_ABSY, 3},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_EOR, C_ABSX, 3},
 {op_LSR, C_ABSX, 3},
 {op_, C_UNK, 1},
 {op_RTS, C_IMP, 1},
 {op_ADC, C_INDX, 2},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_ADC, C_ZERO, 2},
 {op_ROR, C_ZERO, 2},
 {op_, C_UNK, 1},
 {op_PLA, C_IMP, 1},
 {op_ADC, C_IMM, 2},
 {op_ROR, C_ACC, 1},
 {op_, C_UNK, 1},
 {op_JMP, C_IND, 3},
 {op_ADC, C_ABS, 3},
 {op_ROR, C_ABS, 3},
 {op_, C_UNK, 1},
 {op_BVS, C_REL, 2},
 {op_ADC, C_INDY, 2},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_ADC, C_ZEROX, 2},
 {op_ROR, C_ZEROX, 2},
 {op_, C_UNK, 1},
 {op_SEI, C_IMP, 1},
 {op_ADC, C_ABSY, 3},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_ADC, C_ABSX, 3},
 {op_ROR, C_ABSX, 3},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_STA, C_INDX, 2},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_STY, C_ZERO, 2},
 {op_STA, C_ZERO, 2},
 {op_STX, C_ZERO, 2},
 {op_, C_UNK, 1},
 {op_DEY, C_IMP, 1},
 {op_, C_UNK, 1},
 {op_TXA, C_IMP, 1},
 {op_, C_UNK, 1},
 {op_STY, C_ABS, 3},
 {op_STA, C_ABS, 3},
 {op_STX, C_ABS, 3},
 {op_, C_UNK, 1},
 {op_BCC, C_REL, 2},
 {op_STA, C_INDY, 2},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_STY, C_ZEROX, 2},
 {op_STA, C_ZEROX, 2},
 {op_STX, C_ZEROY, 2},
 {op_, C_UNK, 1},
 {op_TYA, C_IMP, 1},
 {op_STA, C_ABSY, 3},
 {op_TXS, C_IMP, 1},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_STA, C_ABSX, 3},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_LDY, C_IMM, 2},
 {op_LDA, C_INDX, 2},
 {op_LDX, C_IMM, 2},
 {op_, C_UNK, 1},
 {op_LDY, C_ZERO, 2},
 {op_LDA, C_ZERO, 2},
 {op_LDX, C_ZERO, 2},
 {op_, C_UNK, 1},
 {op_TAY, C_IMP, 1},
 {op_LDA, C_IMM, 2},
 {op_TAX, C_IMP, 1},
 {op_, C_UNK, 1},
 {op_LDY, C_ABS, 3},
 {op_LDA, C_ABS, 3},
 {op_LDX, C_ABS, 3},
 {op_, C_UNK, 1},
 {op_BCS, C_REL, 2},
 {op_LDA, C_INDY, 2},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_LDY, C_ZEROX, 2},
 {op_LDA, C_ZEROX, 2},
 {op_LDX, C_ZEROY, 2},
 {op_, C_UNK, 1},
 {op_CLV, C_IMP, 1},
 {op_LDA, C_ABSY, 3},
 {op_TSX, C_IMP, 1},
 {op_, C_UNK, 1},
 {op_LDY, C_ABSX, 3},
 {op_LDA, C_ABSX, 3},
 {op_LDX, C_ABSY, 3},
 {op_, C_UNK, 1},
 {op_CPY, C_IMM, 2},
 {op_CMP, C_INDX, 2},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_CPY, C_ZERO, 2},
 {op_CMP, C_ZERO, 2},
 {op_DEC, C_ZERO, 2},
 {op_, C_UNK, 1},
 {op_INY, C_IMP, 1},
 {op_CMP, C_IMM, 2},
 {op_DEX, C_IMP, 1},
 {op_, C_UNK, 1},
 {op_CPY, C_ABS, 3},
 {op_CMP, C_ABS, 3},
 {op_DEC, C_ABS, 3},
 {op_, C_UNK, 1},
 {op_BNE, C_REL, 2},
 {op_CMP, C_INDY, 2},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_CMP, C_ZEROX, 2},
 {op_DEC, C_ZEROX, 2},
 {op_, C_UNK, 1},
 {op_CLD, C_IMP, 1},
 {op_CMP, C_ABSY, 3},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_CMP, C_ABSX, 3},
 {op_DEC, C_ABSX, 3},
 {op_, C_UNK, 1},
 {op_CPX, C_IMM, 2},
 {op_SBC, C_INDX, 2},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_CPX, C_ZERO, 2},
 {op_SBC, C_ZERO, 2},
 {op_INC, C_ZERO, 2},
 {op_, C_UNK, 1},
 {op_INX, C_IMP, 1},
 {op_SBC, C_IMM, 2},
 {op_NOP, C_IMP, 1},
 {op_, C_UNK, 1},
 {op_CPX, C_ABS, 3},
 {op_SBC, C_ABS, 3},
 {op_INC, C_ABS, 3},
 {op_, C_UNK, 1},
 {op_BEQ, C_REL, 2},
 {op_SBC, C_INDY, 2},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_SBC, C_ZEROX, 2},
 {op_INC, C_ZEROX, 2},
 {op_, C_UNK, 1},
 {op_SED, C_IMP, 1},
 {op_SBC, C_ABSY, 3},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_, C_UNK, 1},
 {op_SBC, C_ABSX, 3},
 {op_INC, C_ABSX, 3},
 {op_, C_UNK, 1}
};

static unsigned readWord(unsigned char *mem)
{
    return (((unsigned)mem[1])<<8)| mem[0];
}

//
// Access Functions
//
int len6502(int op)
{
        return op6502s[op].len;
}

void dasm6502(unsigned char *dest,unsigned char *mem,int pc)
{
    char buf[256];
        
    unsigned addr = mem[1];
    opdef_t *op = &op6502s[mem[0]];
    
    switch(op->type)
    {
        case C_IMM:
        sprintf(buf,"#%02X",addr);
        break;
        case C_ACC:
        sprintf(buf,"A");
        break;
        case C_ZERO:
        sprintf(buf,"$%02X",addr);
        break;
        case C_ZEROX:
        sprintf(buf,"$%02X,X",addr);
        break;
        case C_ZEROY:
        sprintf(buf,"$%02X,Y",addr);
        break;
        case C_ABS:
        sprintf(buf,"$%04X",readWord(mem + 1));
        break;
        case C_ABSX:
        sprintf(buf,"$%04X,X",readWord(mem + 1));
        break;
        case C_ABSY:
        sprintf(buf,"$%04X,Y",readWord(mem + 1));
        break;
        case C_IND:
        sprintf(buf,"($%04X)",readWord(mem + 1));
        break;
        case C_INDX:
        sprintf(buf,"($%02X,X)",addr);
        break;
        case C_INDY:
        sprintf(buf,"($%02X),Y",addr);
        break;
        case C_REL:
        if (addr & 0x80)
        {
            addr = (pc + op->len + (0x100 - addr));
        }
        else
        {
            addr = (pc + op->len + addr);
        }
        
        sprintf(buf,"$%04X",addr);
        break;
        default:
            buf[0] = 0;
    }
    sprintf((char *)dest,"%04X : %s %s", pc, op->name, buf);
    
}

